baseURL: https://jmpa.io
languageCode: en-us
title: jmpa.io
theme: jmpa

Params:
  logo: https://raw.githubusercontent.com/jmpa-io/.github/master/logo.png
  favicon: ./favicon.ico
  description: A
  images:
    - >-
      https://raw.githubusercontent.com/jmpa-io/.github/master/logo.png
  custom_css:
    - css/style.css

# menu.
menu:
  main:
    - name: Home
      url: /
      weight: 1

    - name: ğŸ“¦ Tech Stack
      url: /stack
      weight: 2

    - name: ğŸ‹ Docker-101
      url: /docker-101
      weight: 3

    - name: ğŸ¥  Bash-101
      url: /bash-101
      weight: 4

  social:
    - name: GitHub
      url: https://github.com/jmpa-io
      weight: 1

    - name: Email
      url: mailto:support@jmpa.io
      weight: 2

# syntax highlighting.
markup:
  highlight:
    style: dracula
  goldmark:
    renderer:
      unsafe: true

# setup 404s.
# https://moonbooth.com/hugo/custom-404/
redirects:
  - from: /*
    to: /404/
    status: 404

# remove s's in titles.
pluralizeListTitles: false
